version: "3.9"

services:
  postgres:
    image: "postgres:13"
    container_name: postgres
    environment:
      POSTGRES_USER: "grupo_casas_bahia"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "seller"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql